"""Pin the exact tool set the kernel registers through the plugin loader (host tools excluded)."""

from __future__ import annotations

import dataclasses
from types import SimpleNamespace

import pytest

from nanobot.agent.tools.context import ToolContext
from nanobot.agent.tools.exec_session import ExecSessionManager
from nanobot.agent.tools.loader import ToolLoader
from nanobot.agent.tools.registry import ToolRegistry
from nanobot.bus.queue import MessageBus
from nanobot.config.schema import ToolsConfig
from nanobot.session.manager import SessionManager

# Generated by running the loader on the pre-slim code with full gateway-style
# wiring, then removing the scheduler-backed ``cron`` tool and the
# channel-delivery ``message`` tool, plus ``defer_action`` (kernel Task 12,
# design 5a: the deferred-action log). ``my`` is registered manually by
# AgentLoop, not by the loader, so it is not part of this list.
EXPECTED_SLIM_TOOLS = [
    "apply_patch",
    "ask_user",
    "create_goal",
    "defer_action",
    "edit_file",
    "exec",
    "exec_session",
    "find_files",
    "grep",
    "list_dir",
    "list_exec_sessions",
    "list_sessions",
    "read_file",
    "read_session",
    "search_sessions",
    "send_session_message",
    "spawn",
    "update_goal",
    "web_fetch",
    "web_search",
    "write_file",
]


@pytest.fixture
def slim_tool_ctx(tmp_path) -> ToolContext:
    workspace = tmp_path / "workspace"
    workspace.mkdir()
    kwargs = dict(
        config=ToolsConfig(),
        workspace=str(workspace),
        bus=MessageBus(),
        subagent_manager=SimpleNamespace(
            get_running_count=lambda: 0,
            max_concurrent_subagents=4,
        ),
        exec_session_manager=ExecSessionManager(),
        sessions=SessionManager(workspace, sessions_root=tmp_path / "runtime"),
        timezone="UTC",
    )
    return ToolContext(**kwargs)


def test_registered_tool_names_are_exactly_the_slim_set(slim_tool_ctx):
    names = sorted(ToolLoader().load(slim_tool_ctx, ToolRegistry()))
    assert names == EXPECTED_SLIM_TOOLS


def test_host_tools_load_only_for_host_loops(slim_tool_ctx):
    """message/cron/run_cli_app are gateway-owned: absent unless the loop opts in."""
    assert slim_tool_ctx.host_tools is False
    host_ctx = dataclasses.replace(
        slim_tool_ctx, host_tools=True, cron_service=SimpleNamespace(),
    )
    names = set(ToolLoader().load(host_ctx, ToolRegistry()))
    assert {"message", "cron", "run_cli_app"} <= names
    assert names - {"message", "cron", "run_cli_app"} == set(EXPECTED_SLIM_TOOLS)
